import {
  LayoutDashboard,
  Users,
  Briefcase,
  BookOpen,
  Calendar,
  FileText,
  CreditCard,
  MessageSquare,
  Library,
  Bus,
  Box,
  BarChart2,
  Settings,
  GraduationCap,
  Bell,
  ChevronDown,
  Menu,
  X,
  LogOut,
  User,
  Moon,
  Sun,
  Search,
  DollarSign,
  UserPlus,
  Receipt,
  TrendingUp,
  PieChart,
  Landmark,
} from "lucide-react";

const iconMap = {
  "layout-dashboard": LayoutDashboard,
  dashboard: LayoutDashboard,
  users: Users,
  briefcase: Briefcase,
  "book-open": BookOpen,
  book: BookOpen,
  calendar: Calendar,
  "file-text": FileText,
  "credit-card": CreditCard,
  message: MessageSquare,
  "message-square": MessageSquare,
  library: Library,
  bus: Bus,
  box: Box,
  "bar-chart": BarChart2,
  "bar-chart-2": BarChart2,
  settings: Settings,
  graduation: GraduationCap,
  bell: Bell,
  chevronDown: ChevronDown,
  menu: Menu,
  x: X,
  logout: LogOut,
  user: User,
  moon: Moon,
  sun: Sun,
  search: Search,
  "dollar-sign": DollarSign,
  "user-plus": UserPlus,
  receipt: Receipt,
  "trending-up": TrendingUp,
  "pie-chart": PieChart,
  landmark: Landmark,
};

export function getIcon(name) {
  return iconMap[name] || LayoutDashboard;
}
