import {
  LayoutDashboard,
  Users,
  Briefcase,
  BookOpen,
  Calendar,
  FileText,
  CreditCard,
  MessageSquare,
  Library,
  Bus,
  Box,
  BarChart2,
  Settings,
  GraduationCap,
  Bell,
  ChevronDown,
  Menu,
  X,
  LogOut,
  User,
  Moon,
  Sun,
  Search,
} from "lucide-react";

const iconMap = {
  dashboard: LayoutDashboard,
  users: Users,
  briefcase: Briefcase,
  book: BookOpen,
  calendar: Calendar,
  "file-text": FileText,
  "credit-card": CreditCard,
  message: MessageSquare,
  library: Library,
  bus: Bus,
  box: Box,
  "bar-chart": BarChart2,
  settings: Settings,
  graduation: GraduationCap,
  bell: Bell,
  chevronDown: ChevronDown,
  menu: Menu,
  x: X,
  logout: LogOut,
  user: User,
  moon: Moon,
  sun: Sun,
  search: Search,
};

export function getIcon(name) {
  return iconMap[name] || LayoutDashboard;
}
