import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <title>Progress Intellectual Schools</title>
        <meta name="description" content="Progress Intellectual School is committed to providing a nurturing environment that fosters academic excellence and personal growth. Our curriculum focuses on developing well-rounded individuals who are equipped to make a positive impact on the world." />
        <meta name="keywords" content="School, Progress Intellectual " />
        <meta name="author" content="Progress Intellectual Schools" />
        <meta name="robots" content="index, follow" />

        <link rel="icon" href="/images/progressLogo.png" type="image/x-icon" />

        <meta property="og:title" content=" Progress Intellectual Schools" />
        <meta property="og:description" content="Progress Intellectual School is committed to providing a nurturing environment that fosters academic excellence " />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://progressschools.com" />
        <meta property="og:image" content="https://progressschools.com/images/progressLogo.png" />
        <meta property="og:site_name" content=" Progress Intellectual Schools" />

        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Progress Intellectual Schools" />
        <meta name="twitter:description" content="Progress Intellectual School is committed to providing a nurturing environment that fosters academic excellence " />
        <meta name="twitter:image" content="https://progressschools.com/images/progressLogo.png" />
        <meta name="twitter:site" content="@progressintellectualschool" />


        <link rel="canonical" href="https://progressschools.com" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[1600px] mx-auto !bg-white !text-black`}
      >
        {children}
      </body>
    </html>
  );
}
